Update start

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,15 +1,15 @@
 #!/bin/bash
 
 # Colors
-green="\e[38;5;82m"
+green="\e[38;5;87m"
 red="\e[38;5;196m"
 neutral="\e[0m"
-orange="\e[38;5;130m"
-blue="\e[38;5;39m"
+blue="\e[38;5;130m"
+orange="\e[38;5;99m"
 yellow="\e[38;5;226m"
 purple="\e[38;5;141m"
 bold_white="\e[1;37m"
-reset="\e[0m"
+normal="\e[0m"
 pink="\e[38;5;205m"
 print_rainbow() {
     local text="$1"
@@ -48,7 +48,7 @@ cek_status() {
 
 setup_bot() {
     if ! dpkg -s nodejs >/dev/null 2>&1; then
-        curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - || echo -e "${red}Failed to download Node.js setup${neutral}"
+        curl -fsSL https://deb.nodesource.com/setup_23.x | sudo -E bash - || echo -e "${red}Failed to download Node.js setup${neutral}"
         apt-get install -y nodejs || echo -e "${red}Failed to install Node.js${neutral}"
         npm install -g npm@latest
     else
@@ -97,32 +97,18 @@ server_app() {
             echo -e "${red}Nama store tidak boleh kosong. Silakan coba lagi.${neutral}"
         fi
     done
-        while [ -z "$dataqris" ]; do
-        read -p "Masukkan DATA QRIS: " dataqris
-        if [ -z "$dataqris" ]; then
-            echo -e "${red}DATA QRIS tidak boleh kosong. Silakan coba lagi.${neutral}"
-        fi
-    done
-    while [ -z "$merchantid" ]; do
-        read -p "Masukkan MERCHANT ID: " merchantid
-        if [ -z "$merchantid" ]; then
-            echo -e "${red}MERCHANT ID tidak boleh kosong. Silakan coba lagi.${neutral}"
-        fi
-    done
-    while [ -z "$apikey" ]; do
-        read -p "Masukkan API KEY: " apikey
-        if [ -z "$apikey" ]; then
-            echo -e "${red}API KEY tidak boleh kosong. Silakan coba lagi.${neutral}"
+        while [ -z "$keypaydisini" ]; do
+        read -p "Masukkan Keypaydisni: " keypaydisini
+        if [ -z "$keypaydisini" ]; then
+            echo -e "${red}Nama keypaydisini tidak boleh kosong. Silakan coba lagi.${neutral}"
         fi
     done
     rm -f /root/BotVPN/.vars.json
     echo "{
   \"BOT_TOKEN\": \"$token\",
   \"USER_ID\": \"$adminid\",
+  \"PAYDISINI_KEY\": \"$keypaydisini\",
   \"NAMA_STORE\": \"$namastore\",
-  \"DATA_QRIS\": \"$dataqris\",
-  \"MERCHANT_ID\": \"$merchantid\",
-  \"API_KEY\": \"$apikey\"  
   \"PORT\": \"50123\"
 }" >/root/BotVPN/.vars.json
     cat >/etc/systemd/system/sellvpn.service <<EOF
